name: Build Docker images

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [2.4]
        distro: [alpine]
        #distro: [stretch, buster, bullseye, alpine]

    env:
      repo: "govpf/apache"
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Compute tags
      env:
        repo: ${{ env.repo }}
        version: ${{ matrix.version }}
        distro: ${{ matrix.distro }}
      run: |
        TAGS="${repo}:${version}-${distro}"
        if [[ $distro == 'buster' ]]; then
          TAGS+=",${repo}:${version}"
        fi
        echo 'docker_tags<<EOF' >> $GITHUB_ENV
        echo "$TAGS" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: Build
      uses: docker/build-push-action@v6.16.0
      with:
        context: .
        file: ./${{ matrix.version }}/${{ matrix.distro }}/Dockerfile
        platforms: linux/amd64
        pull: true
        push: false
        tags: ${{ env.docker_tags }}
